### ISSUE TITLE
Where can I find the formula for trace_S2?

### ISSUE THREAD

**Issue by Blunde1** [AnestisTouloumis/ShrinkCovMat#1]
In the c++ code, the formula for `tr(S^2)` (an important part of `Y2N` in the [paper on arxiv](https://arxiv.org/abs/1410.4726)) is given as
`double trace_S2 = (trace_S2_1 + trace_S2_2 + trace_S2_3 + trace_S2_4)/(N-1)/(N-1);`
and all four parts have separate expressions that I do not seem to recall from the paper.
What is the reason for not calculating the trace directly from S? 
Can you point me in the correct direction so that I may understand the code and formulas?

**Comment by Blunde1** [comment]
I guess the reason for not calculating the trace directly is that it would be a `p^2` operation, while the implemented method is `pn^2` ?

**Comment by AnestisTouloumis** [comment]
The formula the trace of the square of the sample covariance matrix can be found on Appendix A of this [paper](https://www.sciencedirect.com/science/article/pii/S0047259X14001031) and this quantity can be computed faster without summing the squares of the sample covariance matrix in high-dimensional settings.

**Comment by Blunde1** [comment]
Thanks! It is not immediately obvious exactly how the code and Appendix A of that paper link, but that is likely due to complexity and notation. Will work it out.
