### ISSUE TITLE
Selection of target matrix

### ISSUE THREAD

**Issue by Blunde1** [AnestisTouloumis/ShrinkCovMat#2]
In the paper it is written that
_The main idea is to compare `lambda_hat`, `lambda_hat_I` and `lambda_hat_D` and choose the target matrix with the largest estimated optimal shrinkage intensity. If these estimates are similar and average variance is close to one, then it is sensible to use `Ip` as target matrix. Otherwise, `nu Ip` should be selected when the p sample variances are very close and `diag(S)` when
these vary._
While in the README it is stated that
```
targetselection(normal_group)
#> OPTIMAL SHRINKAGE INTENSITIES FOR THE TARGET MATRIX WITH 
#> Equal variances   : 0.1401 
#> Unit variances    : 0.1125 
#> Unequal variances : 0.14 
#> 
#> SAMPLE VARIANCES 
#> Range   : 0.4714 
#> Average : 0.0882
```
_The estimated optimal shrinkage intensity for the scaled identity matrix is slightly larger than the other two and the sample variances appear to be of similar magnitude. Thus, the scaled identity matrix seems to be the most appropriate target for the covariance estimated._

Is it not the case that the shrinkage intensity for the scaled identity matrix here is smaller than the two others? If then the identity matrix is still chosen as the target, it should be on the basis that all values are "sufficiently small"? Am I understanding this correct, or is it an error in the README?

**Comment by AnestisTouloumis** [comment]
The Unit Variances correspond to the case when the covariance matrix is the correlation matrix (i.e. all variances are equal to 1). The Equal Variances correspond to the scaled identity matrix (i.e. equal variances but not necessarily equal to 1). Hope this makes clarifies the output. I will also try to clarify this further in README.

**Comment by Blunde1** [comment]
Thanks! This helps.
